# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-04-16 22:07
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('job_parser', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='company',
            name='name',
            field=models.CharField(max_length=200, unique=True),
        ),
        migrations.AlterField(
            model_name='jobpost',
            name='url',
            field=models.CharField(max_length=200, unique=True),
        ),
    ]
