# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-04-26 19:52
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('job_parser', '0002_auto_20160416_1707'),
    ]

    operations = [
        migrations.RenameField(
            model_name='postheader',
            old_name='post',
            new_name='job_post',
        ),
    ]
