# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-05-18 16:02
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('job_parser', '0003_auto_20160426_1452'),
    ]

    operations = [
        migrations.AddField(
            model_name='jobpost',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=datetime.datetime(2016, 5, 18, 16, 2, 25, 976000, tzinfo=utc)),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='jobpost',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, default=datetime.datetime(2016, 5, 18, 16, 2, 33, 833000, tzinfo=utc)),
            preserve_default=False,
        ),
    ]
